extends RefCounted

const PHASES := [
	{
		"id": 1,
		"title": "UNA RAYITA PARA DESAYUNAR",
		"joe": "Joe ha decidido que el desayuno equilibrado era opcional.",
		"problem": "Joe empieza con un 90% de colocón. Límpialo y, cuando baje del 70%, descubrirá una manera mucho peor de seguir drogado.",
		"trigger_high": 90.0
	},
	{
		"id": 2,
		"title": "¿QUIÉN HA VACIADO EL CÁRTEL?",
		"joe": "Joe está inquieto porque empieza a notar que se le pasa.",
		"problem": "Al bajar del 70%, el polvo que Joe deja acumulado presiona con más fuerza su colocón. Recoger rápido importa, pero nunca desaparece cocaína del almacén.",
		"trigger_high": 70.0
	},
	{
		"id": 3,
		"title": "OFERTA DEL SUPERMERCADO",
		"joe": "Joe ha comprado una ganga. La ganga contiene serrín, yeso y decisiones.",
		"problem": "Al bajar del 52%, Joe empieza a adulterar las rayitas con serrín, yeso y tiza. El almacén puede quedar completamente bloqueado.",
		"trigger_high": 52.0
	},
	{
		"id": 4,
		"title": "SPRAY NASAL DEL BAZAR",
		"joe": "Joe cree que la humedad es una ciencia y él, por desgracia, es investigador.",
		"problem": "Al bajar del 34%, el spray vuelve a pegar cocaína a la pared y el moco bloquea la minería. Esponjas y catapultas pasan a ser esenciales.",
		"trigger_high": 34.0
	},
	{
		"id": 5,
		"title": "VOLCÁN ZOOLÓGICO",
		"joe": "Joe se rasca, sangra y convierte la nariz en alojamiento rural para bacterias.",
		"problem": "Al bajar del 18%, comienzan hemorragias e infección. Desde aquí la carrera continúa con todas las locuras anteriores activas.",
		"trigger_high": 18.0
	}
]

const UNIT_CATALOG: Array[Dictionary] = [
	{"id":"manual", "name":"MANOS DEL JUGADOR", "type":"HERRAMIENTA MANUAL", "phase":1, "icon":"res://assets/art/gameplay/sprites/cocaine_grain.png", "upgrades":["nails", "continuous_sweep", "click_burst", "click_rhythm"]},
	{"id":"pawn", "name":"GLÓBULO BLANCO", "type":"UNIDAD BÁSICA", "phase":1, "icon":"res://assets/art/gameplay/sprites/pawn_empty.png", "upgrades":["pawn", "pawn_capacity", "smart_clump", "shift", "coord", "pawn_renaissance"]},
	{"id":"surveyor", "name":"LEUCOTOPÓGRAFO DE 1927", "type":"GESTIÓN DE FOSA", "phase":1, "icon":"res://assets/art/gameplay/sprites/pawn_empty.png", "upgrades":["fossa_depth", "fossa_compression"]},
	{"id":"pugilist", "name":"PÚGIL", "type":"EXTRACCIÓN BÁSICA", "phase":1, "icon":"res://assets/art/gameplay/sprites/pawn_empty.png", "upgrades":["puncher", "punch_union", "punch_training", "punch_speed", "punch_power", "bronchial_rage", "punch_reserves", "punch_combo", "uranium_wraps", "punch_collective", "punch_renaissance"]},
	{"id":"ram", "name":"LEUCOCARNERO", "type":"EXTRACCIÓN DE EMBESTIDA", "phase":2, "icon":"res://assets/art/gameplay/sprites/leukocyte_ram.png", "upgrades":["ram", "ram_power", "ram_speed"]},
	{"id":"leukophant", "name":"LEUCOFANTE", "type":"EXTRACCIÓN PESADA", "phase":3, "icon":"res://assets/art/gameplay/sprites/leukocyte_elephant.png", "upgrades":["elephant", "elephant_power"]},
	{"id":"hammer", "name":"LEUCOMARTILLO", "type":"EXTRACCIÓN NEUMÁTICA", "phase":4, "icon":"res://assets/art/gameplay/sprites/leukocyte_hammer.png", "upgrades":["hammer", "hammer_power"]},
	{"id":"plasma_cannon", "name":"CAÑÓN DE PLASMA NAPIAL", "type":"ARTILLERÍA EXPERIMENTAL", "phase":4, "icon":"res://assets/art/gameplay/sprites/plasma_cannon.png", "upgrades":["plasma_cannon", "plasma_power"]},
	{"id":"meteor", "name":"NEUTRÓFILO METEORITO", "type":"EXTRACCIÓN AEROESPACIAL", "phase":5, "icon":"res://assets/art/gameplay/sprites/neutrophil_meteor.png", "upgrades":["meteor", "meteor_power"]},
	{"id":"supersaiyan", "name":"LEUCOCITO SUPERSAIYAN", "type":"ARMA ABSURDA DEFINITIVA", "phase":5, "icon":"res://assets/art/gameplay/sprites/leukocyte_supersaiyan.png", "upgrades":["supersaiyan", "supersaiyan_power"]},
	{"id":"breaker", "name":"CASCO AZUL", "type":"ADAPTACIÓN AL APELMAZADO", "phase":1, "icon":"res://assets/art/gameplay/sprites/pawn_specialist_empty.png", "upgrades":["breaker", "breaker_power"]},
	{"id":"detector", "name":"QUIMIORRECEPTOR", "type":"ADAPTACIÓN A IMPUREZAS", "phase":3, "icon":"res://assets/art/gameplay/sprites/pawn_detector_empty.png", "upgrades":["detector", "wall_scan", "sorting"]},
	{"id":"sponge", "name":"MACRÓFAGO ESPONJA", "type":"ADAPTACIÓN AL SPRAY", "phase":4, "icon":"res://assets/art/gameplay/sprites/sponge_yellow.png", "upgrades":["sponge", "sponge_power"]},
	{"id":"platelet", "name":"PLAQUETA", "type":"REPARACIÓN TISULAR", "phase":5, "icon":"res://assets/art/gameplay/sprites/platelet.png", "upgrades":["platelets", "repair"]},
	{"id":"handler", "name":"CUIDADOR CON GUANTES", "type":"CONTROL BACTERIANO", "phase":5, "icon":"res://assets/art/gameplay/sprites/pawn_handler_empty.png", "upgrades":["handlers", "signals"]},
	{"id":"catapult", "name":"CATAPULTA MUCOLÍTICA", "type":"MÁQUINA DE ADAPTACIÓN", "phase":4, "icon":"res://assets/art/gameplay/sprites/mucus_catapult.png", "upgrades":["catapult", "catapult_power"]},
	{"id":"cart", "name":"CARRITO VESICULAR", "type":"TRANSPORTE", "phase":1, "icon":"res://assets/art/gameplay/sprites/vesicular_cart.png", "upgrades":["cart", "cart_reinforced", "cart_upgrade", "cart_speed", "cart_freight", "cart_bulk", "cart_tanker", "cart_renaissance"]},
	{"id":"leukox", "name":"MUGIDÓFILO DE CARGA", "type":"TRANSPORTE PESADO", "phase":2, "icon":"res://assets/art/gameplay/sprites/leukox.png", "upgrades":["ox_convoy", "ox_capacity", "ox_speed", "ox_heavy_capacity", "ox_vault_capacity", "ox_plasma_capacity"]},
	{"id":"train", "name":"EXPRESO LEUCOCITARIO", "type":"TRANSPORTE INTERFOSA", "phase":5, "icon":"res://assets/art/gameplay/sprites/leukocyte_express.png", "upgrades":["train", "train_speed"]},
	{"id":"storage", "name":"ALMACENAMIENTO", "type":"INFRAESTRUCTURA", "phase":1, "icon":"res://assets/art/gameplay/infrastructure/storage_container.png", "upgrades":["container", "container_capacity", "warehouse", "silo", "silo_capacity", "vault", "vault_capacity", "vault_reserve", "plant", "plant_buffer", "plant_capacity"]}
]

const UPGRADES := [
	{"id":"nails", "phase":1, "name":"UÑAS DE QUERATINA", "desc":"Cada nivel da un salto completo de escala manual.", "base":15.0, "growth":4.0, "kind":"click", "power":1.0, "max":8},
	{"id":"pawn", "phase":1, "unlock_at":15.0, "name":"GLÓBULO BLANCO RECOLECTOR", "desc":"Contrata tu primer peón —y después más— para recoger y transportar nieve por su cuenta.", "base":35.0, "growth":3.2, "kind":"pawn", "power":1.0, "max":10},
	{"id":"continuous_sweep", "phase":1, "unlock_at":55.0, "name":"BARRIDO CONTINUO", "desc":"Mantén pulsado sobre el montón para enviar granos a la caja sin machacar el ratón.", "base":80.0, "growth":4.0, "kind":"manual_sweep", "power":1.0, "max":3},
	{"id":"click_burst", "phase":1, "unlock_at":90.0, "name":"NUDILLOS DE QUERATINA", "desc":"Cada cierto ritmo de clics repite varias veces toda tu potencia manual.", "base":700.0, "growth":2.4, "kind":"click_burst", "power":1.0, "max":5},
	{"id":"container", "phase":1, "unlock_at":80.0, "name":"CONTENEDOR DE NIEVE DE EMERGENCIA", "desc":"Sustituye el cajón de quinientas unidades por un almacén de mil.", "base":250.0, "growth":1.0, "kind":"storage", "power":1000.0, "max":1},
	{"id":"fossa_depth", "phase":1, "requires_upgrade":"warehouse", "name":"FOSA SUBMUCOSA", "desc":"Construye una zona profunda de vertido. El Leucotopógrafo aparece y muestra en tiempo real cuánto espacio queda: el límite sube de 75K a 600K.", "base":60000.0, "growth":1.0, "kind":"fossa_depth", "power":600000.0, "max":1},
	{"id":"fossa_compression", "phase":3, "requires_upgrade":"fossa_depth", "name":"PRENSA DEL SUMIDERO", "desc":"Comprime nieve en profundidad sin alterar su valor: caben 100M, 50B y 100T. Cada salto acompaña a una nueva escala de extracción.", "base":10000000.0, "growth":100.0, "kind":"fossa_compression", "power":1.0, "max":3},
	{"id":"cart", "phase":1, "requires_upgrade":"container", "name":"CARRITO VESICULAR", "desc":"Un transportista separado recoge doce unidades sin minar la pared.", "base":900.0, "growth":1.0, "kind":"transport_cart", "power":12.0, "max":1},
	{"id":"pawn_capacity", "phase":1, "requires_upgrade":"pawn", "name":"MEMBRANA CON BOLSILLOS", "desc":"Cada peón carga una bola más por viaje; también mejora los peones que compres después.", "base":900.0, "growth":3.2, "kind":"pawn_capacity", "power":1.0, "max":9},
	{"id":"smart_clump", "phase":1, "requires_upgrades":["cart", "breaker"], "name":"APELMAZADO INTELIGENTE", "desc":"Tras aprender de los cascos azules, los glóbulos compactan granos normales en bolas de carga blandas.", "base":2400.0, "growth":3.4, "kind":"smart_clump", "power":1.0, "max":5},
	{"id":"puncher", "phase":1, "requires_puncher_unlock":true, "name":"CÉLULA PÚGIL EN PRÁCTICAS", "desc":"Contrata un púgil. La cuadrilla está limitada a cuatro.", "base":900.0, "growth":3.0, "kind":"autoclicker", "power":1.0, "max":4},
	{"id":"container_capacity", "phase":1, "requires_upgrades":["container", "cart"], "name":"DOBLE FONDO FARMACÉUTICO", "desc":"Amplía el contenedor de mil a cinco mil antes de multiplicar la carga del carrito.", "base":900.0, "growth":1.0, "kind":"storage", "power":5000.0, "max":1},
	{"id":"cart_reinforced", "phase":1, "requires_upgrades":["cart", "container_capacity"], "name":"EJES VESICULARES REFORZADOS", "desc":"El mismo carrito lleva sesenta unidades. Exige haber ampliado antes el almacén.", "base":3200.0, "growth":1.0, "kind":"transport_capacity", "power":60.0, "max":1},
	{"id":"warehouse", "phase":1, "requires_upgrade":"cart_reinforced", "name":"ALMACÉN ALVEOLAR MODULAR", "desc":"Acopla módulos al contenedor y abre un límite de cien mil unidades.", "base":4500.0, "growth":1.0, "kind":"storage", "power":100000.0, "max":1},
	{"id":"cart_upgrade", "phase":1, "requires_upgrades":["warehouse", "puncher"], "name":"CARGA VESICULAR COMPRIMIDA", "desc":"El carrito prensa la carga y transporta trescientas unidades.", "base":18000.0, "growth":1.0, "kind":"transport_capacity", "power":300.0, "max":1},
	{"id":"punch_union", "phase":1, "requires_upgrades":["cart", "puncher"], "name":"SINDICATO DEL PUÑO", "desc":"Dos púgiles básicos se incorporan juntos a la cuadrilla.", "base":7500.0, "growth":1.0, "kind":"punch_union", "power":2.0, "max":1},
	{"id":"punch_training", "phase":1, "requires_upgrade":"punch_union", "name":"PROTEÍNA DE MÉDULA", "desc":"Triplica la fuerza de cada púgil sin adelantar su evolución visual.", "base":14000.0, "growth":1.0, "kind":"punch_training", "power":3.0, "max":1},
	{"id":"punch_speed", "phase":1, "requires_upgrade":"punch_training", "name":"TURNO DE NOCHE DEL GIMNASIO", "desc":"Reduce el descanso de la cuadrilla básica de cuatro a dos segundos y medio.", "base":26000.0, "growth":1.0, "kind":"auto_speed", "power":0.625, "max":1},
	{"id":"shift", "phase":1, "requires_any_upgrades":["cart_upgrade", "punch_training"], "name":"AUTOVÍA LINFÁTICA PEATONAL", "desc":"Acelera un 50% los peones sin multiplicar también todos los vehículos.", "base":30000.0, "growth":1.0, "kind":"speed", "power":1.0, "max":1},
	{"id":"cart_speed", "phase":1, "requires_upgrade":"cart_upgrade", "name":"RODAMIENTOS DE PLAQUETA", "desc":"Dos niveles de ruedas mejores mantienen al carrito competitivo sin acelerar a toda la logística.", "base":45000.0, "growth":4.0, "kind":"transport_speed", "power":0.4, "max":2},
	{"id":"punch_power", "phase":2, "requires_upgrade":"punch_training", "name":"CARNÉ DE PESO LEUCOCITARIO", "desc":"Cada nueva fase permite una evolución visual y multiplica por diez el golpe base.", "base":25000.0, "growth":10.0, "kind":"auto_power", "power":10.0, "max":3},
	{"id":"bronchial_rage", "phase":2, "requires_upgrade":"punch_training", "name":"RABIA DE TURNO DOBLE", "desc":"Al entrar en la segunda fase, toda la cuadrilla pega el doble de fuerte.", "base":18000.0, "growth":1.0, "kind":"punch_multiplier", "power":2.0, "max":1},
	{"id":"punch_reserves", "phase":2, "requires_upgrades":["bronchial_rage", "warehouse"], "name":"BECARIOS DEL TURNO PARTIDO", "desc":"Incorpora dos púgiles básicos más sin consumir una evolución visual.", "base":65000.0, "growth":1.0, "kind":"punch_reserves", "power":2.0, "max":1},
	{"id":"punch_combo", "phase":2, "requires_upgrades":["punch_reserves", "silo"], "name":"COMBO DE BAR DE GUARDIA", "desc":"Cada tercera ronda de la cuadrilla golpea dos veces de una sola vez.", "base":220000.0, "growth":1.0, "kind":"punch_combo", "power":2.0, "max":1},
	{"id":"uranium_wraps", "phase":2, "requires_upgrade":"punch_combo", "name":"VENDAS DE URANIO HOMEOPÁTICO", "desc":"Reduce otro 25% el descanso entre rondas. La etiqueta asegura que es natural.", "base":650000.0, "growth":1.0, "kind":"punch_late_speed", "power":0.75, "max":1},
	{"id":"punch_collective", "phase":2, "requires_upgrade":"uranium_wraps", "name":"PUÑO COLECTIVO DE CONVENIO", "desc":"Triplica toda la fuerza de la cuadrilla y mantiene a los púgiles relevantes junto al Leucocarnero.", "base":1200000.0, "growth":1.0, "kind":"punch_collective", "power":3.0, "max":1},
	{"id":"ram", "phase":2, "requires_upgrades":["silo", "uranium_wraps"], "name":"LEUCOCARNERO", "desc":"Tras los escalones medios de la cuadrilla, una célula con cuernos embiste por quinientas mil unidades.", "base":1500000.0, "growth":1.0, "kind":"ram", "power":500000.0, "max":1},
	{"id":"ram_power", "phase":2, "requires_upgrades":["ram", "silo_capacity"], "name":"CUERNOS DE QUERATINA BALÍSTICA", "desc":"Refuerza los cuernos: las embestidas pasan de 500K a 1M y después a 2,5M.", "base":2500000.0, "growth":3.0, "kind":"ram_power", "power":1.0, "max":2},
	{"id":"ram_speed", "phase":2, "requires_upgrade":"ram", "requires_levels":{"ram_power":2}, "name":"PEZUÑAS DE MÉDULA COMPETITIVA", "desc":"Con los cuernos completos, reduce la preparación entre embestidas de ocho a seis segundos.", "base":8000000.0, "growth":1.0, "kind":"ram_speed", "power":0.75, "max":1},
	{"id":"click_rhythm", "phase":2, "requires_upgrade":"click_burst", "name":"RITMO DE BAÑO", "desc":"Necesitas menos clics para provocar cada ráfaga manual.", "base":800.0, "growth":2.0, "kind":"click_rhythm", "power":1.0, "max":4},
	{"id":"coord", "phase":2, "requires_septum":true, "name":"TRABAJO EN CADENA", "desc":"Reparte peones entre las dos fosas y prioriza los atascos.", "base":550.0, "growth":2.4, "kind":"coordination", "power":1.0, "max":2},
	{"id":"breaker", "phase":1, "requires_compaction":true, "name":"CASCO AZUL REGLAMENTARIO", "desc":"Convierte un glóbulo disponible en especialista para abrir apelmazados.", "base":850.0, "growth":2.25, "kind":"specialist", "power":1.0, "max":8},
	{"id":"breaker_power", "phase":1, "requires_upgrade":"breaker", "name":"PICO DE SEGURIDAD DUDOSA", "desc":"Refuerza el casco, el pico y la confianza laboral de todos los especialistas.", "base":2600.0, "growth":3.0, "kind":"specialist_power", "power":1.0, "max":5},
	{"id":"silo", "phase":2, "requires_upgrades":["warehouse", "cart_upgrade"], "name":"SILO DE NIEVE ESTRATÉGICA", "desc":"El primer salto industrial almacena hasta dos millones de unidades.", "base":80000.0, "growth":1.0, "kind":"storage", "power":2000000.0, "max":1},
	{"id":"cart_freight", "phase":2, "requires_upgrade":"silo", "name":"PALETIZADO VESICULAR", "desc":"Sin añadir otro vehículo, eleva la carga del carrito a mil quinientas unidades.", "base":120000.0, "growth":1.0, "kind":"transport_capacity", "power":1500.0, "max":1},
	{"id":"cart_bulk", "phase":2, "requires_upgrades":["cart_freight", "silo"], "name":"REMOLQUE VESICULAR DE GRANEL", "desc":"El mismo carrito aumenta su carga a seis mil unidades y recupera relevancia.", "base":300000.0, "growth":1.0, "kind":"transport_capacity", "power":6000.0, "max":1},
	{"id":"ox_convoy", "phase":2, "requires_upgrade":"cart_bulk", "name":"MUGIDÓFILO DE CARGA", "desc":"Una célula-buey tira de tres carros y transporta cuarenta mil unidades.", "base":250000.0, "growth":1.0, "kind":"transport_ox", "power":40000.0, "max":1},
	{"id":"silo_capacity", "phase":2, "requires_upgrade":"ox_convoy", "name":"SILO CON CARRIL DE BORRACHOS", "desc":"Amplía el silo hasta diez millones antes de mejorar el convoy pesado.", "base":750000.0, "growth":1.0, "kind":"storage", "power":10000000.0, "max":1},
	{"id":"cart_tanker", "phase":2, "requires_upgrades":["cart_bulk", "silo_capacity"], "name":"CUBA VESICULAR PRESURIZADA", "desc":"Una última ampliación permite al carrito mover veinticuatro mil unidades por viaje.", "base":900000.0, "growth":1.0, "kind":"transport_capacity", "power":24000.0, "max":1},
	{"id":"ox_capacity", "phase":2, "requires_upgrade":"ox_convoy", "name":"MUGIDO DE CARGA ESCALONADA", "desc":"Dos mejoras elevan al Mugidófilo de cuarenta mil a ciento cincuenta mil y seiscientas mil unidades.", "base":350000.0, "growth":2.5, "kind":"transport_ox_capacity", "power":1.0, "max":2},
	{"id":"ox_speed", "phase":2, "requires_upgrade":"ox_convoy", "name":"PEZUÑAS DE TRÁFICO PESADO", "desc":"Dos niveles aceleran solamente al Mugidófilo, sin multiplicar a todos los porteadores.", "base":500000.0, "growth":3.0, "kind":"transport_speed", "power":0.5, "max":2},
	{"id":"ox_heavy_capacity", "phase":2, "requires_upgrades":["ox_convoy", "silo_capacity"], "requires_levels":{"ox_capacity":2}, "name":"RUMIA DE ALTO TONELAJE", "desc":"Con el silo ampliado, el Mugidófilo sube de seiscientas mil a dos millones y finalmente seis millones y medio.", "base":2000000.0, "growth":2.5, "kind":"transport_ox_capacity", "power":1.0, "max":2},
	{"id":"vault", "phase":3, "requires_upgrade":"silo_capacity", "name":"BÓVEDA DE NIEVE PRESURIZADA", "desc":"Reutiliza el silo como una cámara de cien millones para financiar extracción pesada.", "base":8000000.0, "growth":1.0, "kind":"storage", "power":100000000.0, "max":1},
	{"id":"vault_capacity", "phase":3, "requires_upgrade":"vault", "name":"BÓVEDA DE NIEVE HIPERBÁRICA", "desc":"Refuerza la misma bóveda hasta mil millones antes de la reserva final de fase.", "base":75000000.0, "growth":1.0, "kind":"storage", "power":1000000000.0, "max":1},
	{"id":"vault_reserve", "phase":3, "requires_upgrade":"vault_capacity", "requires_levels":{"ox_vault_capacity":3}, "name":"RESERVA ESTRATOSFÉRICA DE NAPIA", "desc":"Una última cámara de tres mil millones sostiene al Leucofante y al Mugidófilo de final de fase.", "base":650000000.0, "growth":1.0, "kind":"storage", "power":3000000000.0, "max":1},
	{"id":"ox_vault_capacity", "phase":3, "requires_upgrades":["ox_convoy", "vault"], "requires_levels":{"ox_heavy_capacity":2}, "name":"RUMIA DE BÓVEDA", "desc":"Cuatro escalones elevan la carga de 6,5M a 20M, 100M, 500M y finalmente 2B.", "base":12000000.0, "growth":3.0, "kind":"transport_ox_capacity", "power":20000000.0, "max":4},
	{"id":"detector", "phase":3, "name":"QUIMIORRECEPTORES", "desc":"Detectan serrín, yeso y tiza: los demás peones dejan de llevar basura al almacén.", "base":2000000.0, "growth":2.5, "kind":"detector", "power":1.0, "max":3},
	{"id":"wall_scan", "phase":3, "requires_upgrade":"detector", "name":"RADIOGRAFÍA DE NAPIA", "desc":"Después de analizar la porquería, revela la resistencia exacta de las paredes.", "base":8000000.0, "growth":1.0, "kind":"wall_scan", "power":1.0, "max":1},
	{"id":"sorting", "phase":3, "name":"RECONOCIMIENTO MOLECULAR", "desc":"Reduce la proporción de impurezas que atasca cada turno.", "base":3000000.0, "growth":3.0, "kind":"sorting", "power":0.08, "max":3},
	{"id":"sponge", "phase":4, "name":"MACRÓFAGO ESPONJA", "desc":"Absorbe la película azul del spray; mientras exista, la pared no se puede minar.", "base":200000000.0, "growth":3.0, "kind":"sponge", "power":40.0, "max":2},
	{"id":"sponge_power", "phase":4, "requires_upgrade":"sponge", "name":"ESPONJOSIDAD PROHIBIDA", "desc":"La esponja crece y multiplica las unidades de spray absorbidas cada segundo.", "base":500000000.0, "growth":3.0, "kind":"sponge_power", "power":1.8, "max":5},
	{"id":"elephant", "phase":3, "requires_upgrades":["ram_speed", "vault", "fossa_compression"], "requires_levels":{"ram_power":2, "fossa_compression":1}, "name":"LEUCOFANTE", "desc":"La siguiente escala: avanza despacio y descarga quince millones cada veinte segundos.", "base":20000000.0, "growth":1.0, "kind":"elephant", "power":15000000.0, "max":1},
	{"id":"elephant_power", "phase":3, "requires_upgrade":"elephant", "name":"MEMORIA DE LEUCOFANTE", "desc":"Cuatro recuerdos cada vez menos responsables elevan el cabezazo hasta 2,4B.", "base":45000000.0, "growth":2.6, "kind":"elephant_power", "power":1.0, "max":4},
	{"id":"hammer", "phase":4, "requires_upgrades":["elephant", "plant"], "requires_levels":{"elephant_power":4}, "name":"LEUCOMARTILLO", "desc":"Un glóbulo con orejeras recorre la fosa a saltos y martillea 600M cada cuatro segundos.", "base":3000000000.0, "growth":1.0, "kind":"hammer", "power":600000000.0, "max":1},
	{"id":"hammer_power", "phase":4, "requires_upgrade":"hammer", "name":"COMPRESOR DE MÉDULA", "desc":"Duplica el golpe neumático del Leucomartillo sin añadir otra unidad.", "base":5000000000.0, "growth":1.0, "kind":"hammer_power", "power":2.0, "max":1},
	{"id":"platelets", "phase":5, "name":"PLAQUETAS TURBO", "desc":"Convoca dos reparadoras coral que priorizan las heridas abiertas.", "base":5000000000.0, "growth":2.0, "kind":"platelet", "power":1.0, "max":6},
	{"id":"repair", "phase":5, "requires_upgrade":"platelets", "name":"PLAQUETAS GRAPADORAS", "desc":"Evoluciona la reparación de puntada a sutura industrial.", "base":8000000000.0, "growth":3.0, "kind":"repair", "power":2.5, "max":5},
	{"id":"plasma_cannon", "phase":4, "requires_upgrades":["elephant", "plant_buffer", "fossa_compression"], "requires_levels":{"elephant_power":4, "ox_plasma_capacity":3, "fossa_compression":2}, "name":"CAÑÓN DE PLASMA NAPIAL", "desc":"Tras agotar el Leucofante y su logística, condensa cinco mil millones en una esfera azul.", "base":8000000000.0, "growth":1.0, "kind":"plasma_cannon", "power":5000000000.0, "max":1},
	{"id":"plasma_power", "phase":4, "requires_upgrade":"plasma_cannon", "name":"BOBINA DE FUSIÓN MUCOSAL", "desc":"Tres bobinas elevan cada descarga de 5B a 20B, 80B y finalmente 320B; la última exige la planta de fusión.", "base":15000000000.0, "growth":4.0, "kind":"plasma_power", "power":1.0, "max":3},
	{"id":"meteor", "phase":5, "requires_upgrades":["plasma_cannon", "plant_buffer"], "requires_levels":{"plasma_power":2, "plant_buffer":1}, "name":"NEUTRÓFILO METEORITO", "desc":"Una célula atada a un cohete impacta por 100B y regresa fingiendo que era el plan.", "base":40000000000.0, "growth":1.0, "kind":"meteor", "power":100000000000.0, "max":1},
	{"id":"meteor_power", "phase":5, "requires_upgrade":"meteor", "name":"QUEROSENO LINFÁTICO", "desc":"Duplica el impacto del cohete celular hasta 200B cada doce segundos.", "base":80000000000.0, "growth":1.0, "kind":"meteor_power", "power":2.0, "max":1},
	{"id":"plant", "phase":4, "requires_upgrades":["ox_convoy", "vault_reserve"], "requires_septum":true, "name":"PLANTA DE NIEVE INDUSTRIAL", "desc":"Una refinería en la otra fosa eleva el almacén de 3B a 10B.", "base":2000000000.0, "growth":1.0, "kind":"storage", "power":10000000000.0, "max":1},
	{"id":"plant_buffer", "phase":4, "requires_upgrade":"plant", "name":"TOLVAS DE CATARRO INDUSTRIAL", "desc":"Dos ampliaciones sostienen 50B y luego 150B antes de entrar en la fase final.", "base":6000000000.0, "growth":4.0, "kind":"storage", "power":50000000000.0, "max":2},
	{"id":"ox_plasma_capacity", "phase":4, "requires_upgrades":["ox_vault_capacity", "plant"], "requires_levels":{"ox_vault_capacity":4}, "name":"ESTÓMAGO DE PLASMA LOGÍSTICO", "desc":"Tres escalones elevan el mismo Mugidófilo a 5B, 20B y 80B por viaje.", "base":1500000000.0, "growth":4.0, "kind":"transport_ox_capacity", "power":5000000000.0, "max":3},
	{"id":"plant_capacity", "phase":5, "requires_upgrade":"plant_buffer", "requires_levels":{"plant_buffer":2}, "name":"PLANTA DE FUSIÓN SUPERSAIYAN", "desc":"Tres niveles amplían la planta a 500B, 5T y finalmente 50T.", "base":100000000000.0, "growth":5.0, "kind":"storage", "power":500000000000.0, "max":3},
	{"id":"supersaiyan", "phase":5, "requires_upgrades":["plasma_cannon", "plant_capacity", "fossa_compression"], "requires_levels":{"plasma_power":3, "plant_capacity":2, "fossa_compression":3}, "name":"LEUCOCITO SUPERSAIYAN", "desc":"La última unidad: carga durante un siglo emocional y lanza un billón de daño.", "base":1000000000000.0, "growth":1.0, "kind":"supersaiyan", "power":1000000000000.0, "max":1},
	{"id":"supersaiyan_power", "phase":5, "requires_upgrade":"supersaiyan", "name":"GRITOS DE CINCO EPISODIOS", "desc":"Dos gritos elevan el Kamehameha de 1T a 10T y finalmente 100T.", "base":4000000000000.0, "growth":7.5, "kind":"supersaiyan_power", "power":10.0, "max":2},
	{"id":"handlers", "phase":5, "name":"GUANTES DE PROTECTORA", "desc":"Cuidadores que recogen bacterias sin dejar que les muerdan.", "base":6000000000.0, "growth":2.0, "kind":"handler", "power":1.0, "max":4},
	{"id":"signals", "phase":5, "name":"SEÑALES QUÍMICAS", "desc":"Coordina cuidadores, plaquetas y peones sin una sola reunión.", "base":10000000000.0, "growth":2.2, "kind":"signals", "power":0.12, "max":3},
	{"id":"catapult", "phase":4, "name":"CATAPULTA MUCOLÍTICA", "desc":"Cada máquina lanza un glóbulo y arranca 600 unidades de moco cada 2,8 segundos.", "base":250000000.0, "growth":3.0, "kind":"catapult", "power":600.0, "max":2},
	{"id":"catapult_power", "phase":4, "requires_upgrade":"catapult", "name":"TENSIÓN DE MEMBRANA", "desc":"Duplica el impacto de todos los proyectiles mucolíticos.", "base":400000000.0, "growth":2.0, "kind":"catapult_power", "power":2.0, "max":4},
	{"id":"train", "phase":5, "requires_upgrades":["plant", "plant_buffer"], "requires_septum":true, "name":"EXPRESO LEUCOCITARIO", "desc":"Carga en la fosa derecha y cruza por túneles hasta la planta izquierda.", "base":25000000000.0, "growth":1.0, "kind":"transport_train", "power":1.0, "max":1},
	{"id":"train_speed", "phase":5, "requires_upgrade":"train", "name":"HORARIO DE CERCANÍAS MITOCONDRIAL", "desc":"Dos mejoras aceleran el Expreso un 60% y después un 150% respecto a su velocidad inicial.", "base":500000000000.0, "growth":8.0, "kind":"train_speed", "power":1.0, "max":2},
	{"id":"pawn_renaissance", "phase":5, "requires_levels":{"smart_clump":5}, "name":"HIPERAPELMAZADO DE BOLSILLO", "desc":"Segunda juventud del peón: sus bolas blandas pasan de 21 a 55 y después a 144 granos.", "base":50000000000.0, "growth":5.0, "kind":"pawn_renaissance", "power":1.0, "max":2},
	{"id":"cart_renaissance", "phase":5, "requires_upgrades":["cart_tanker", "plant_buffer"], "name":"ITV VESICULAR CUÁNTICA", "desc":"El carrito clásico vuelve con carga industrial: 500M y después 5B por viaje.", "base":50000000000.0, "growth":5.0, "kind":"cart_renaissance", "power":1.0, "max":2},
	{"id":"punch_renaissance", "phase":5, "requires_upgrade":"punch_collective", "requires_levels":{"punch_power":3}, "name":"PLAN DE PENSIONES DEL PUÑO", "desc":"La vieja cuadrilla se niega a jubilarse: multiplica su daño por 100 y después por 1.000.", "base":50000000000.0, "growth":5.0, "kind":"punch_renaissance", "power":1.0, "max":2}
]
